### ISSUE TITLE
Update Subproperty

### ISSUE THREAD

**Issue by sigmoid-azoth** [chhoumann/MetaEdit#33]
Is there a way to update a yaml subproperty via something like `update("metadata.description", "test", "📂 nonhierarchical/Untitled.md")` ? If not, could this be added?

Example yaml
```yaml
---
metadata:
    aliases     : []
    datetime    : { created     : 2021-07-22T17:30:05-04:00 }
    description : 
    scope       : personal
    status      : { reviewed    : false }
    tags        : [NOTE/OBJECT]
    title       : Untitled
    type        : 
    uuid        : 1bd559d1-2d3d-4416-9109-082f5ebb03e6
source  :
    template: "[[📁 templates/📄 new uri 🔗.md]]"
    version : 1626988597970
uri     : 
    label   : 
    data    : scheme://www.example.null
    type    : bookmark

---
```
